# Generated by Django 4.1.5 on 2023-01-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='technologie',
            new_name='technology',
        ),
    ]
