# Generated by Django 4.1.5 on 2023-01-13 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='date',
        ),
        migrations.AddField(
            model_name='posts',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2023, 1, 13, 19, 36, 20, 301258, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='posts',
            name='category',
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ManyToManyField(related_name='posts', to='blog.category'),
        ),
    ]
